joostkremers/ebib

ebib.el

I use ebib as a quickly cite selector,  so I need the feature, which can quit ebib without ask yes or no.

Add `ebib-force-quit' command

---

ebib.el

string-black-p was introduced at Emacs 24.4.

Fix for Emacs 24.3

---

ebib-utils.el
ebib.el

Previously, the viewer name in ebib-file-associations needed to be
precisely an executable to be found on exec-path. Now it can also
contain command-line options, and a "%s" where the file path needs to
go.
If the string contains no "%s", it falls-back to the original behavior,
and is therefore backwards compatible.

Allow command-line options in ebib-file-associations.

---

ebib-utils.el
ebib.el

Because it often doesn't look well to display the original field content, this pull request enables customizable display of fields in the index buffer, such as
- remove the latex markups, mainly '{}', in the title field
- abbreviate long author/journal fields
- use symbols to indicate the url/doi/file/notes/group/...
In addition, I would like that the columns shown in the index buffer is independent of bibtex or biblatex fields, i.e., a column, which has its own name, can be associated to one field, multiple fields, or other information (e.g. note/group/...). For example, a 3-character wide column named "www" can be defined as `("Doi" "Url") 3)`, which displays the information provided by the Doi field, or the Url field if the Doi field is empty. I would like to know your opinions, …

Enhance the display of the index buffer

---

org-ebib.el

It is helpful to display the details of ebib links in org mode without switching to ebib buffers. Since there seems no convenient way to make citation string in ebib, this patch currently depends on the reftex library. The dependence on reftex is not required and can be removed if ebib has similar function.

Show details when moving the mouse onto ebib links

---

ebib.el

The defvar defines ebib--keywords-history but that is never used.  Seems to have been overlooked when renaming variables back in 2014/2015.

Bug fix: use ebib--keywords-history instead of ebib-keyword-history

---

ebib.el

The package always complains about non-existing entry types such as `phdthesis` or `masterthesis` when loading a database, even though these types exist (as aliases) with biblatex.

Always include aliases

---

ebib-utils.el

It help explore bib file from dired without setting ebib-file-search-dirs.

add: open file relative to ebib--cur-db

---

ebib-utils.el

The canonical URL is "https://www.aclweb.org/anthology/ID",
the PDF URL is "https://www.aclweb.org/anthology/ID.pdf".
Also remove potentially superfluous slash at the end as "ID/" is also
a valid URL and might have slipped in for some users.

Add ACL anthology download transformation.

---

ebib-utils.el
ebib.el
manual/ebib.text
test/ebib-test.el

Hi, I implemented #144.
Without this little feature
And now with this feature enabled (defaults to disabled) the user gets is told how the arguments will be used

Show format string to user when prompting for arguments

---

ebib.el

The function ebib-add-keywords-to-entry called ebib--maybe-add-keywords-to-canonical-list with strings, instead of with a list of strings. This means that 'K a' fails with an error and keywords can only be added by editing the keyword field.

Fixed ebib-add-keywords-to-entry

---

ebib.el

There are many bibtex entries that sport both 'and' and 'AND' as name separator. Moreover, many of them also split over various lines or have extra spaces to have a more visually appealing format. Consider this in ebib--create-author/editor-collection when splitting the author names.

Split author/editor names in a case-insensitive fashion

---

ebib-keywords.el

Sometimes imported entries contain keywords separated by pure commas, such as in "key1,key2". When the value of ebib-keywords-separator is ", ", the keys are not properly split. This behavior is inconsistent with the use of "[[:space:]]*" to trim the split list.

Ignore spaces when splitting keywords to list

---

ebib-keywords.el
ebib.el

When bibtex entries are created, some fields have multiple lines that are indented for readability in the *.bib files. Unfortunately, those spaces, which appear only on the 2nd and later lines, get inserted into the database. This patch eliminates those leading spaces before adding the 19 spaces that are used for displaying multiline fields, making the indentation right.

Fix multiline spaces

---

ebib-utils.el
ebib.el

Knocked this up just now and I thought it might be useful. I started using strings for the first time today, and realised that once you get going, it can be hard to remember what strings display what and know what information you actually have in an entry.
This PR displays the expanded values of abbreviations and concatenations in the entry buffer, rather than the raw text itself (similar to crossreferenced field behaviour). The fields are still marked as special, and the expanded text comes up in `ebib-alias-face`, which seemed appropriate (and also meant I didn't have to define a new face). Editing the value still brings up the actual value in the entry itself (the short abbreviations and concatenations with '#'). To do this I had to add an option to `ebib-get-field-value`, but its …

Display abbreviation values in entry buffer

---

ebib-utils.el

usually completions are not shown without slash

add slash to ebib-import-directory

---

ebib-utils.el
ebib.el

Fixe #236.
A number of internal api changes, roughly as [here](https://github.com/joostkremers/parsebib/issues/16#issuecomment-1004645284).
The overall effect is that it is now possible to expand a string (as might be found in a field value) into its final printable version recursively, following all the rules that bib(la)tex would. In particular:
- multiple `#` characters (or `#` at the end of a string) are not allowed
- strings consisting entirely of digits [do not need to be expanded](https://tex.stackexchange.com/questions/629260/which-fields-have-to-be-braced-or-quoted-in-bib-files-why-does-year-not-ha/629266#629266)
- braces and quote marks can be escaped with `\`
- braces must match, unless they appear inside "quo{tes"
Must say, the code isn't pretty, but it does work and I'm quite …

Recursive strings

---

ebib-utils.el

Quick fix for a bad bug I noticed today. Biblatex allows quite complex date specifications, including using `/`,`:` and `-` to separate different types of elemtents. The regex needed to include these.

ebib-get-field-value: fix date regex to allow [:-/] chars

---

ebib-utils.el

Fix #245. My past self didn't understand arrays and strings in elisp properly and the function is actually entirely redundant.
Commit message:
> Strings just are arrays, so this doesn't do anything useful, and adds
> extra dependency for users.

ebib--expand-string: remove redundant `dbus-byte-array-to-string`

---

ebib-utils.el
ebib.el

As [promised](https://github.com/joostkremers/ebib/pull/237#issuecomment-1006879964):
- add a toggle-raw action to the string buffer, and a flag to signal raw strings. 
- display complete expansions in the string buffer where relevant (that is, only for those strings for which this is useful)
Everything (including the effects of changing strings use in other strings) should update in real time.
This is on the same branch as the last PR because it was really the same project (and because, by the time I realised they were the same branch, I was already three commits in :shrug:)

Improvements to the string buffer to support raw/recursive strings

---

ebib.el

I have a status icon in my index display for whether an entry has notes, and I realised it didn't update when I deleted a note (which it should). I realised this was because when notes are deleted, the relevant entries' keys are never removed from the running list kept in `ebib--notes-list`. Fix this.
Original commit message:
> When a note file is deleted, remove the current entry's key from
> ebib's internal list of which entries have notes.

ebib-delete-field-contents: keep ebib--notes-list up to date

---

ebib.el

Fix #249. Commit message below:
> The `string' rx construct is relatively and not present in
> still-supported older versions of emacs. Use an alternative method
> which should achieve the same thing.

ebib--redisplay-strings-buffer: adjust rx for back-compatibility

---

ebib-utils.el
ebib.el

This PR is based on #258. Now Emacs Lisp functions could be used as file opener for Ebib.
Related docstring, `defcustom` type and function logic have been modified. Additionally, `ebib--call-file-viewer` will signal an error if an invalid file handler is assigned now.
The related section in the Ebib Manual is not modified due to my poor English skills, my different literature style with the original author, and my lack of the knowledge to hook the `manual/ebib.text` file with the website.

Enable Emacs Lisp function as file handler in `ebib-file-associations`

---

ebib-utils.el

Replace `ebib-clean-TeX-markup` with `parsebib-clean-TeX-markup`. Seems to have been missed in the original replacements.

ebib--process-reference-template: use new parsebib-clean-TeX-markup

---

ebib-ivy.el
ebib-utils.el
ebib.el

The code for editing these fields at the moment produces an experience similar enough to `completing-read-multiple` that I expect them to work that way (and integrate with things like vertico) but different enought that it's annoying and jarring when they don't. I think it would be fairly simple to use `completing-read-multiple` in the code and get all the features currently available in these fields. If anything, I think using it might even simplify the code. Here's a version of file-name completion for editting the file field which seems to work pretty well:
```elisp
(defun ebib--edit-file-field ()
"Edit the \"file\" field'.
Filenames are added to the standard file field separated by
`ebib-filename-separator'.  The first directory in
`ebib-file-search-dirs' is used as the start …
```

Feature request: use `completing-read-multiple` for editting fields with multiple values and completion (file, publishers etc.)

---

ebib-notes.el
ebib-utils.el
ebib.el

Replaces #264.
Use Emacs-standard button library to make some text clickable, replacing the previous mechanism. Reasons are given in the commit messages and #264. Make `crossref` fields clickable, to follow the crossref (similar to opening a file).

Use button functionality to make some fields clickable (now including `crossref`)

---

ebib.el

Fix #275.
This is a slightly hacky way of providing compatibility with versions of Emacs without `object-intervals`. I've done this (rather than properly refactoring the code) because I think that in a few years, when `object-intervals is part of the emacs most people are using, it would be a good idea to go back (the operation is relatively slow and the current code is ugly, so going to a native solution which does exactly what we need, written in C, would be perfect).

ebib--get-field-highlighted: replace `object-intervals'

---

ebib-biblio.el

This is an alternative to the (seemingly more complex) #241.
Instead, it re-uses the callback function defined for selection import for DOI-forwarded data.
It uses the standard `bibtex` library to get the key of the first entry, and after importing, sets the current key & updates ebib buffers.

Center on the first entry found in biblio-imported entries

---

ebib-reading-list.el

(ebib--reading-list-locate-item "some_key") would match an entry with key "some_key123".

Avoid matching a key substring in ebib--reading-list-locate-item.

---

ebib-utils.el

I've started using a .bib file to hold data for my CV. When I'm working on the TeX (or bbx, cbx, dbx, cls, etc.) in the CV folder, I the only bib file I want to edit is that one. I never really want to edit it otherwise. So, it's useful if this variable can be set locally (using .dir-locals). To avoid having to confirm that it's safe every time, I've added a sensible test for safety.

ebib-preload-bib-files: add a safe-local-variable property

---

ebib-utils.el

This is an improvement on #296.
Original commit message:
> This is useful because the variable definition, including the `:safe:' declaration, is only loaded as the package is loaded. If the user sets the variable locally (e.g. in `Local Variables') and then visits that file in a new session before opening ebib for the first time, the safe predicate won't be recognised and the user is prompted for whether to use the new value. Using an autoload is the solution to this suggested in the elisp manual `(elisp) File Local Variables'.

ebib-preload-bib-files: autoload safety predicate

---

ebib.el

Fixes comments in #270.
Sorry about this, small error on my part.

ebib-history-forward: fix setting head

---

ebib.el

I realised that emacs has a built in system for allowing extensions and external packages to interoperate with registers and jumping. Using this system is better than defining a command like `ebib-jump-to-register`, because you can still use various other register functions inside ebib.
For example, if I store a window config in a register, then open and use ebib, then want to restore the window config, I can just use `jump-to-register` and select the right register. Except that if ebib shadows the binding for `jump-to-register` with it's own similar command, I have to invoke `jump-to-register` manually. The Emacs Way is instead to define a method for ebib-type jumpable objects which are stored in registers, and let `jump-to-register` despatch on that type. That's what this PR does.

Standardise entry jump

---

ebib.el

In all major modes, apply dir local variables. Fix #304 
-----
This works for me. I've applied to all major modes.

hack dir local variables in major modes

---

ebib.el
manual/ebib.text

This is done to a) prevent oddities if the doi is a whole URL but not using dx.doi.org as the resolver, and b) allow for alternative resolvers (e.g., https://oadoi.org/) to be used.
Additionally, it switches the default resolver to `https://doi.org`, which is the DOI Foundation's preferred default resolver.

Extract DOI from doi field & allow customization of resolver

---

ebib.el

I wrote [this package](https://github.com/Hugo-Heagren/clever-cite) recently. It's operation requires that for each PDF in my library, a file local variable be set, holding that file's bib key in my database (it's actually more flexible than that, but this is the simple way I'm using it at the moment). I've set this up with all my existing files.
My ebib workflow is that I add new entries to my database, then I use `ebib-import-file` to add files to them. I want to be able to automate the setting of the file-local variable as part of the import process (similarly to how file names for imported files are automatically generated).
To achieve this, and allow (user-customisable) customisation of the process, I have added an abnormal hook to the import function.
I could then do this, and thus …

Import file hook

---

ebib.el

In `ebib-entry-mode`, if point is not on any field, attempting to move to the next field signals an error:
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
ebib-next-field(1)
funcall-interactively(ebib-next-field 1)
command-execute(ebib-next-field)
```
The cause of this behavior is that `next-single-property-change` returns `nil` when there is no next `ebib-field-end` change, and the code immediately does `(1+ field-end)`.
To reproduce:
1. Open an entry buffer.
2. `M-x end-of-buffer`.
3. Press the down arrow (`ebib-next-field`).
- Add a `nil` guard in `ebib-next-field`:
- If `next-single-property-change` returns `nil`, do nothing (and beep when invoked interactively), avoiding the error.
- Preserve existing behavior of beeping when the move would …

guard `ebib-next-field` against `nil` `field-end`
